root: true
env:
  browser: true
  es6: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - jest
rules:
  "@typescript-eslint/no-explicit-any": off
  lines-between-class-members: off
  object-curly-newline: off
  class-methods-use-this: off
  quotes: off
  import/no-unresolved: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-param-reassign: off
  no-unused-vars: off
  max-len: off
